package:
  name: zimg
  version: {{ datetime.datetime.today().strftime('%Y.%m.%d.%H') }}

source:
  path: ../src/3rdparty/build/conda_build

build:
  number: 0

requirements:
  build:
#    - git
#    - cmake
#    - ninja

  host:
    - qt
    - mkl-devel
    - tbb-devel
    - python x.x
    - numpy

  run:
    - python
    - numpy >=1.20
    - qt
    - mkl
    - tbb

test:

outputs:

about:
  home: https://feng-lab.github.io
  license: proprietary - fenglab
  license_family: PROPRIETARY
