package:
  name: zimg
  version: {{ datetime.datetime.today().strftime('%Y.%m.%d.%H') }}

source:
  path: ../src/3rdparty/build/conda_build

build:
  number: 0

requirements:
  build:
#    - git
#    - cmake
#    - ninja

  host:
    - python x.x

  run:
    - python

test:

outputs:

about:
  home: https://feng-lab.github.io
  license: proprietary - fenglab
  license_family: PROPRIETARY
