#pragma once

#include "zswc.h"

#include <string>
#include <vector>

namespace nim::neutube {

// Port of `ZSwcTree::save` SWC formatting used by neuTube.
//
// Writes:
// - fixed header "#Generated by NeuTu (https://github.com/janelia-flyem/NeuTu)\n"
// - optional comment lines prefixed with '#'
// - node lines in depth-first order: "%d %d %g %g %g %g %d\n"
//
// This function resorts IDs before writing (matching legacy behavior).
void writeSwcLegacyNeuTu(ZSwc* tree, const std::string& filePath, const std::vector<std::string>& comments = {});

} // namespace nim::neutube
