#include "zneutubeswcwriter.h"

#include "zneutubeswcops.h"

#include "zlog.h"

#include <cstdio>

namespace nim::neutube {

namespace {

[[nodiscard]] const char* commentHeader()
{
  return "#Generated by NeuTu (https://github.com/janelia-flyem/NeuTu)\n";
}

} // namespace

void writeSwcLegacyNeuTu(ZSwc& tree, const std::string& filePath, const std::vector<std::string>& comments)
{
  if (tree.empty()) {
    LOG(WARNING) << "Empty tree. No file saved.";
    return;
  }

  resortId(tree);

  std::FILE* fp = std::fopen(filePath.c_str(), "w");
  if (fp == nullptr) {
    LOG(ERROR) << "Failed to open SWC file for writing: " << filePath;
    return;
  }

  std::fprintf(fp, "%s", commentHeader());

  for (const auto& c : comments) {
    std::fprintf(fp, "#%s\n", c.c_str());
  }

  for (auto it = tree.cbegin(); it != tree.cend(); ++it) {
    const int id = static_cast<int>(it->id);
    const int type = static_cast<int>(it->type);
    const int parentId = static_cast<int>(ZSwc::parentID(it));
    std::fprintf(fp, "%d %d %g %g %g %g %d\n", id, type, it->x, it->y, it->z, it->radius, parentId);
  }

  std::fclose(fp);
}

} // namespace nim::neutube
