#include "zswcwriter.h"

#include "zexception.h"
#include "zioutils.h"
#include "zswcops.h"

#include "zlog.h"

#include <ios>
#include <string_view>

namespace nim {

namespace {

[[nodiscard]] std::string_view commentHeader()
{
  return "#Generated by NeuTu (https://github.com/janelia-flyem/NeuTu)\n";
}

} // namespace

void writeSwcLegacyNeuTu(ZSwc& tree, const QString& filePath, const std::vector<std::string>& comments)
{
  if (tree.empty()) {
    LOG(WARNING) << "Empty tree. No file saved.";
    return;
  }

  try {
    writeSwcLegacyNeuTuOrThrow(tree, filePath, comments);
  }
  catch (const std::exception& e) {
    LOG(ERROR) << "Failed to write SWC file: " << filePath << " (" << e.what() << ")";
  }
}

void writeSwcLegacyNeuTuOrThrow(ZSwc& tree, const QString& filePath, const std::vector<std::string>& comments)
{
  if (tree.empty()) {
    throw ZException("writeSwcLegacyNeuTuOrThrow: Empty tree. No file saved.");
  }

  resortId(tree);

  try {
    std::ofstream fs = openOFStream(filePath, std::ios_base::out | std::ios_base::trunc);
    fs.exceptions(std::ios::badbit | std::ios::failbit);

    fs << commentHeader();

    for (const auto& c : comments) {
      fs << fmt::format("#{}\n", c);
    }

    for (auto it = tree.cbegin(); it != tree.cend(); ++it) {
      const int id = static_cast<int>(it->id);
      const int type = static_cast<int>(it->type);
      const int parentId = static_cast<int>(ZSwc::parentID(it));
      fs << fmt::format("{} {} {:.6g} {:.6g} {:.6g} {:.6g} {}\n", id, type, it->x, it->y, it->z, it->radius, parentId);
    }

    fs.flush();
  }
  catch (const ZException&) {
    throw;
  }
  catch (const std::exception& e) {
    throw ZException(fmt::format("writeSwcLegacyNeuTuOrThrow: Failed to write SWC file: {} ({})", filePath, e.what()));
  }
}

} // namespace nim
