#!/bin/sh

currDIR="$( cd -P "$( dirname "$0" )" && pwd )"
cd $currDIR

DIRECTORY="../build-atlas"

if [[ -d "$DIRECTORY" && ! -L "$DIRECTORY" ]] ; then
    cd $DIRECTORY
else
    DIRECTORY="../build-atlas-Desktop-Release/atlas"
	if [[ -d "$DIRECTORY" && ! -L "$DIRECTORY" ]] ; then
    	cd $DIRECTORY
    else
    	echo "Can not find release directory. Abort."
    	exit
    fi
fi

if [ -e "Atlas.app" ]; then
	/Users/feng/Qt/5.7/clang_64/bin/macdeployqt Atlas.app #-verbose=3
	if [ -e "atlas.app.new.zip" ]; then
		rm atlas.app.new.zip
	fi
	zip -qr atlas.app.new.zip Atlas.app
	rm -r Atlas.app
  cp -f atlas.app.new.zip "/Users/feng/Google Drive/jinny'lab/software/atlas.app.new.zip"
else
	echo "Atlas.app not build yet."
fi