#!/bin/sh

currDIR="$( cd -P "$( dirname "$0" )" && pwd )"
cd $currDIR

DIRECTORY="../atlas-build-Desktop-Release/atlas"

if [[ -d "$DIRECTORY" && ! -L "$DIRECTORY" ]] ; then
    cd $DIRECTORY
else
    DIRECTORY="../build-atlas-Desktop-Release/atlas"
	if [[ -d "$DIRECTORY" && ! -L "$DIRECTORY" ]] ; then
    	cd $DIRECTORY
    else
    	echo "Can not find release directory. Abort."
    	exit
    fi
fi

if [ -e "atlas.app" ]; then
	/Users/feng/Qt/5.6/clang_64/bin/macdeployqt atlas.app #-verbose=3
	if [ -e "atlas.app.new.zip" ]; then
		rm atlas.app.new.zip
	fi
	zip -qr atlas.app.new.zip atlas.app
	rm -r atlas.app
  cp -f atlas.app.new.zip "/Users/feng/Google Drive/jinny'lab/software/atlas.app.new.zip"
else
	echo "atlas.app not build yet."
fi