package:
  name: conda-opencv
  version: {{ datetime.datetime.today().strftime('%Y.%m.%d.%H') }}

source:
  path: ../src/3rdparty/build/conda_build

build:
  number: 0

requirements:
  build:

  host:
    - python x.x
    - numpy
    - mkl
    - tbb

  run:
    - python x.x
    - numpy >=1.20
    - mkl
    - tbb
    - libstdcxx-ng # [linux]
    - libgcc-ng # [linux]

test:

outputs:

about:
  home: http://opencv.org/
  license: Apache
  license_family: Apache
  summary: Computer vision and machine learning software library.
