name: macOS

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

#env:
  # DEVELOPER_DIR: /Applications/Xcode_12.3.app/Contents/Developer

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: check envs
        shell: bash -l {0}
        run: |
          ls -n /Applications/ | grep Xcode*
          env

#      - uses: actions/checkout@v2
#        with:
#          fetch-depth: 1
#          submodules: 'recursive'
#
#      - uses: conda-incubator/setup-miniconda@v2
#        with:
#          auto-update-conda: true
#          python-version: 3.8
#          miniconda-version: "latest"
#          activate-environment: test
#
#      - name: install conda packages
#        shell: bash -l {0}
#        run: |
#          conda info
#          conda list
#          conda update --all -y
#          conda install tbb-devel mkl-devel qt numpy python wget anaconda-client conda-build conda-verify
#          conda list
#          conda clean --all -y
#
#      - name: download Qt
#        shell: bash -l {0}
#        env:
#          CI_DOWNLOAD_SERVER: ${{ secrets.CI_DOWNLOAD_SERVER }}
#        run: |
#          conda info
#          cd ~
#          pwd
#          wget -q $CI_DOWNLOAD_SERVER/${{ runner.os }}/dep-Qt-2021-01-17.zip
#          unzip -q dep-Qt-2021-01-17.zip
#          rm dep-Qt-2021-01-17.zip
#
#      - name: download intel
#        shell: bash -l {0}
#        env:
#          CI_DOWNLOAD_SERVER: ${{ secrets.CI_DOWNLOAD_SERVER }}
#        run: |
#          conda info
#          cd ~
#          pwd
#          wget -q $CI_DOWNLOAD_SERVER/${{ runner.os }}/dep-intel-2021-01-17.zip
#          unzip -q dep-intel-2021-01-17.zip
#          rm dep-intel-2021-01-17.zip
#          cd $GITHUB_WORKSPACE/src/3rdparty
#          mkdir build
#          ls -la
#
#      - uses: actions/cache@v2
#          id: cache-deps
#          with:
#            path: $GITHUB_WORKSPACE/src/3rdparty/build
#            key: ${{ runner.os }}-deps-2021-01-21
#
#      - name: download deps
#        if: steps.cache-deps.outputs.cache-hit != 'true'
#        shell: bash -l {0}
#        env:
#          CI_DOWNLOAD_SERVER: ${{ secrets.CI_DOWNLOAD_SERVER }}
#        run: |
#          conda info
#          cd ~
#          pwd
#          wget -q $CI_DOWNLOAD_SERVER/common/atlas-deps-2021-01-21.zip
#          unzip -q atlas-deps-2021-01-21.zip
#          rm atlas-deps-2021-01-21.zip
#
#      - name: build deps
#        if: steps.cache-deps.outputs.cache-hit != 'true'
#        shell: bash -l {0}
#        env:
#          ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
#        run: |
#          conda info
#          cd $GITHUB_WORKSPACE
#          pwd
#          python util/build_ext_libs.py all
#          conda config --set anaconda_upload yes
#          conda-build --token $ANACONDA_API_TOKEN --user fenglab conda-opencv-recipe
#
#      - name: build
#        shell: bash -l {0}
#        run: |
#          conda info
#          cd $GITHUB_WORKSPACE
#          pwd
#          python util/build_atlas.py
#
#      - name: download test data
#        shell: bash -l {0}
#        env:
#          CI_DOWNLOAD_SERVER: ${{ secrets.CI_DOWNLOAD_SERVER }}
#        run: |
#          conda info
#          cd ~
#          pwd
#          wget -q $CI_DOWNLOAD_SERVER/common/atlas-test-data-2021-01-18.zip
#          unzip -q atlas-test-data-2021-01-18.zip
#          rm atlas-test-data-2021-01-18.zip
#
#      - name: test
#        shell: bash -l {0}
#        env:
#          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
#          SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
#          SSH_SERVER: ${{ secrets.SSH_SERVER }}
#          SSH_PORT: ${{ secrets.SSH_PORT }}
#          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
#          SSH_DEPLOY_PATH: ${{ secrets.SSH_DEPLOY_PATH }}
#          CI_CACHE_PATH: ${{ secrets.CI_CACHE_PATH }}
#        run: |
#          conda info
#          cd $GITHUB_WORKSPACE
#          pwd
#          python util/deploy_atlas.py
#          mkdir -p ~/.ssh/
#          echo "$SSH_PRIVATE_KEY" > ~/.ssh/private.key
#          sudo chmod 600 ~/.ssh/private.key
#          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
#          cd $GITHUB_WORKSPACE/deploy
#          rsync -avv --delete -e 'ssh -p $SSH_PORT -i ~/.ssh/private.key' ${{ runner.os }} $SSH_USERNAME@$SSH_SERVER:$SSH_DEPLOY_PATH/packages/
#          rsync -tvv -e 'ssh -p $SSH_PORT -i ~/.ssh/private.key' AtlasInstaller*.zip $SSH_USERNAME@$SSH_SERVER:$SSH_DEPLOY_PATH/installers/
#          cd ../src/3rdparty
#          zip --quiet --recurse-paths --symlinks build-cache-${{ runner.os }}.zip build
#          ssh -p $SSH_PORT -i ~/.ssh/private.key $SSH_USERNAME@$SSH_SERVER "rm -f $CI_CACHE_PATH/build-cache-${{ runner.os }}.zip"
#          scp -P $SSH_PORT -i ~/.ssh/private.key build-cache-${{ runner.os }}.zip $SSH_USERNAME@$SSH_SERVER:$CI_CACHE_PATH/
#
#      - name: build and upload conda zimg
#        shell: bash -l {0}
#        env:
#          ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
#        run: |
#          conda info
#          cd $GITHUB_WORKSPACE
#          pwd
#          python util/build_ext_libs.py conda-zimg
#          conda config --set anaconda_upload yes
#          conda-build --token $ANACONDA_API_TOKEN --user fenglab zimg-recipe
