name: windows

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: check envs
        shell: pwsh
        run: |
          Get-CimInstance -Class Win32_logicaldisk
          dir env:
#          Install-Module -Name PSFolderSize -AcceptLicense -Force -Verbose -Scope "CurrentUser"
#          Get-FolderSize -Path 'C:\Program Files'
#          Get-FolderSize -Path 'C:\hostedtoolcache\windows'
#          Get-CimInstance -Class Win32_logicaldisk

      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
          submodules: 'recursive'

      - name: use C
        shell: pwsh
        run: |
          Copy-Item -Path $Env:GITHUB_WORKSPACE -Destination ~/atlas -Recurse
          cd ~
          Get-ChildItem

      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.8
          miniconda-version: "latest"
          activate-environment: test

      - name: install conda packages
        shell: pwsh
        run: |
          conda info
          conda list
          conda update --all -y
          conda install tbb-devel mkl-devel qt numpy python anaconda-client conda-build conda-verify
          conda list
          conda clean --all -y
          choco install wget unzip rsync

#      - uses: actions/cache@v2
#        id: cache-qt
#        with:
#          path: ~/Qt
#          key: ${{ runner.os }}-qt-2021-01-18

      - name: download qt
#        if: steps.cache-qt.outputs.cache-hit != 'true'
        shell: pwsh
        run: |
          conda info
          cd ~
          Get-Location
          wget.exe -q https://fenglab.xyz/static/deps/windows/dep-qt-2021-01-18.zip
          unzip.exe -q dep-qt-2021-01-18.zip
          Get-ChildItem
          Remove-Item dep-qt-2021-01-18.zip

#      - uses: actions/cache@v2
#        id: cache-intel
#        with:
#          path: ~/intel
#          key: ${{ runner.os }}-intel-2021-01-18

      - name: download intel
#        if: steps.cache-intel.outputs.cache-hit != 'true'
        shell: pwsh
        run: |
          conda info
          cd ~
          Get-Location
          wget.exe -q https://fenglab.xyz/static/deps/windows/dep-intel-2021-01-18.zip
          unzip.exe -q dep-intel-2021-01-18.zip
          Get-ChildItem
          Remove-Item dep-intel-2021-01-18.zip
          Rename-Item windows intel

      - uses: actions/cache@v2
        id: cache-deps
        with:
          path: ~/atlas/src/3rdparty/build
          key: ${{ runner.os }}-deps-2021-01-19

      - name: download deps
        if: steps.cache-deps.outputs.cache-hit != 'true'
        shell: pwsh
        run: |
          conda info
          cd ~
          Get-Location
          Get-ChildItem
          wget.exe -q https://fenglab.xyz/static/deps/common/atlas-deps-2021-01-19.zip
          unzip.exe -q atlas-deps-2021-01-19.zip
          Get-ChildItem
          Remove-Item atlas-deps-2021-01-19.zip

      - name: build deps
        if: steps.cache-deps.outputs.cache-hit != 'true'
        shell: pwsh
        env:
          ANACONDA_PASSWORD: ${{ secrets.ANACONDA_PASSWORD }}
        run: |
          conda info
          cd ~/atlas
          Get-Location
          python util/build_ext_libs.py all
          anaconda login --username fenglab --password "$Env:ANACONDA_PASSWORD"
          conda config --set anaconda_upload yes
          conda-build conda-opencv-recipe
          conda-build zimg-recipe

      - name: build
        shell: pwsh
        run: |
          conda info
          cd ~/atlas
          Get-Location
          python util/build_atlas.py

#      - uses: actions/cache@v2
#        id: cache-test-data
#        with:
#          path: ~/atlas_test_data
#          key: atlas-test-data-2021-01-18

      - name: download test data
#        if: steps.cache-test-data.outputs.cache-hit != 'true'
        shell: pwsh
        run: |
          conda info
          cd ~
          Get-Location
          Get-ChildItem
          wget.exe -q https://fenglab.xyz/static/deps/common/atlas-test-data-2021-01-18.zip
          unzip.exe -q atlas-test-data-2021-01-18.zip
          Remove-Item atlas-test-data-2021-01-18.zip

      - name: test
        shell: pwsh
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
          SSH_SERVER: ${{ secrets.SSH_SERVER }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          SSH_DEPLOYPATH: ${{ secrets.SSH_DEPLOYPATH }}
          SSH_KEY_PATH: ~/private.key
        run: |
          conda info
          cd ~/atlas
          Get-Location
          python util/deploy_atlas.py
          New-Item -Path ~/.ssh -ItemType Directory -Force
          $Env:SSH_PRIVATE_KEY | Out-File ../private.key
          Icacls ../private.key /Inheritance:r
          Icacls ../private.key /Grant:r "$Env:Username":"(R)"
          $Env:SSH_KNOWN_HOSTS | Out-File ~/.ssh/known_hosts
          cd ~/atlas/deploy
#          rsync -av --delete -e 'ssh -p $Env:SSH_PORT -i $Env:SSH_KEY_PATH' windows $Env:SSH_USERNAME@$Env:SSH_SERVER:$Env:SSH_DEPLOYPATH/packages/
#          rsync -av -e 'ssh -p $Env:SSH_PORT -i $Env:SSH_KEY_PATH' AtlasInstaller*.zip $Env:SSH_USERNAME@$Env:SSH_SERVER:$Env:SSH_DEPLOYPATH/installers/
